### ISSUE TITLE
Release latest to Clojars

### ISSUE THREAD

**Issue by bripkens** [clojurewerkz/gizmo#11]
I'd like to try Gizmo in a project, but use it with the upgraded set of dependencies as introduced in https://github.com/clojurewerkz/gizmo/commit/7ba52d4515defa79cee5300e3264c6c21ea3818f. Could you please release a `1.0.0-alpha5`?

Thanks!

**Comment by ifesdjeen** [comment]
sec

**Comment by ifesdjeen** [comment]
deployed `1.0.0-alpha5-SNAPSHOT`
